services:
    db:
        build: db/
        environment:
            POSTGRES_PASSWORD: pass
        ports:
            - 5432:5432
    web:
        depends_on:
            - db
        build: .
        volumes:
            - ./attest:/app/attest
        environment:
            FLASK_APP: attest.server
        command:
            ['flask', 'run', '--host=0.0.0.0']
    nginx:
        depends_on:
            - web
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:8080
